# version: '3.8'

# services:
#   mysql:
#     image: mysql:8.0
#     container_name: mysql
#     environment:
#       MYSQL_DATABASE: mydb
#       MYSQL_USER: myuser
#       MYSQL_PASSWORD: mypassword
#       MYSQL_ROOT_PASSWORD: rootpassword
#     volumes:
#       - mysql_data:/var/lib/mysql
#     ports:
#       - "3306:3306"
#     restart: unless-stopped
#     command: --log-bin-trust-function-creators=1 
     
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin:latest
#     container_name: phpmyadmin
#     environment:
#       PMA_HOST: mysql
#       MYSQL_ROOT_PASSWORD: rootpassword
#     ports:
#       - "5050:80"
#     depends_on:
#       - mysql
#     restart: unless-stopped


# volumes:
#   mysql_data:



version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
